import pickle
from whisper_segmenter import WhisperSegmenter
import os
from tqdm import tqdm

def load_video_list(file_path):
    videos = []
    with open(file_path, "r") as f:
        for line in f:
            path, label = line.strip().split()
            videos.append((path, int(label)))
    return videos


def build_segments(video_list, output_file, segmenter):
    dataset_segments = []
    for video_path, label in tqdm(video_list, desc="Segmenting Videos"):
        try:
            utterances = segmenter.segment_audio(video_path)
            for u in utterances:
                dataset_segments.append(
                    {
                        "video_path": video_path,
                        "start": u["start"],
                        "end": u["end"],
                        "text": u["text"],
                        "label": label,
                    }
                )

        except Exception as e:
            print(f"Failed processing {video_path}: {e}")

    with open(output_file, "wb") as f:
        pickle.dump(dataset_segments, f)
    print(f"Saved {len(dataset_segments)} segments → {output_file}")


if __name__ == "__main__":
    from pathlib import Path
    
    dir_path = "preprocessing/segments"
    os.makedirs(dir_path, exist_ok=True)
    
    # We want to output to final/segments/
    train_video_output_path = Path(dir_path + "/train_segments.pkl")
    val_video_output_path = Path(dir_path + "/val_segments.pkl")
    
    
    # Ensure the segments directory exists before writing to it
    train_video_output_path.parent.mkdir(parents=True, exist_ok=True)

    print("Loading video lists...")
    # Load from the text files generated by phase1 (now living in the exact same folder as this script)
    phase1_dir = Path(__file__).parent
    train_videos = load_video_list(phase1_dir / "train_videos.txt")
    val_videos = load_video_list(phase1_dir / "val_videos.txt")
    
    segmenter = WhisperSegmenter()
    print("Starting TRAIN segmentation")
    build_segments(train_videos, train_video_output_path, segmenter)
    print("Finished TRAIN segmentation")
    
    print("Starting VAL segmentation")
    build_segments(val_videos, val_video_output_path, segmenter)
    print("Finished VAL segmentation")